# import libraries

In [1]:
#import libraries
import pandas as pd
print('pandas: %s' % pd.__version__)

import xarray as xr
print('xarray: %s' % xr.__version__)

pd.options.display.max_columns = None
pd.set_option('display.max_rows', 150)

import numpy as np
print('geopandas: %s' % np.__version__)



# Data manipulation
import pandas as pd # for data manipulation
print('pandas: %s' % pd.__version__) # print version
import numpy as np # for data manipulation
print('numpy: %s' % np.__version__) # print version

import decimal
from decimal import Decimal

pandas: 1.4.3
xarray: 0.20.1
geopandas: 1.23.1
pandas: 1.4.3
numpy: 1.23.1

# import datas

In [2]:
test_set = pd.read_csv('data_with_newtarget/test_set_with_newtarget.csv')
validation_set = pd.read_csv('data_with_newtarget/validation_set_with_newtarget.csv')
traning_set = pd.read_csv('data_with_newtarget/traning_set_with_newtarget.csv')

#training with yestersay lsm
traning_df = traning_set['newlsm']
traning_df
ndf = traning_df.iloc[1:]
ndf.loc[4268771,] = 0.0
nd = ndf.reset_index()
del nd["index"]
nd =nd.rename(columns={'newlsm': 'Tomorrow_lsm'})
df2 = traning_set.assign(Tomorrow_lsm=nd)
del df2["Unnamed: 0"]

#validation with yestersay lsm
validation_df = validation_set['newlsm']
ndf_val = validation_df.iloc[1:]
ndf_val.loc[688402,] = 0.0
nd_val = ndf_val.reset_index()
del nd_val["index"]
nd_val =nd_val.rename(columns={'newlsm': 'Tomorrow_lsm'})
df3 = validation_set.assign(Tomorrow_lsm=nd_val)
del df3["Unnamed: 0"]


#test with yestersay lsm
test_df = test_set['newlsm']
ndf_test = test_df.iloc[1:]
ndf_test.loc[539487,] = 0.0
nd_test = ndf_test.reset_index()
del nd_test["index"]
nd_test =nd_test.rename(columns={'newlsm': 'Tomorrow_lsm'})
df4 = test_set.assign(Tomorrow_lsm=nd_test)
del df4["Unnamed: 0"]


training_set_wt = df2
validation_set_wt =df3
test_set_wt = df4

In [3]:
training_set_wt

,time,latitude,longitude,vo,r,u_200,u_850,v_200,v_850,ttr,sst,lsm,newlsm,Tomorrow_lsm
0,1980-01-01,0.0,20.0,0.000007,80.761185,1.909660,-3.323872,1.687164,-1.823624,-247.54074,0.00000,0.0,0.0,0.0
1,1980-01-01,0.0,22.5,0.000004,80.703650,1.165733,-2.844494,1.060593,-1.991425,-240.00592,0.00000,0.0,0.0,0.0
2,1980-01-01,0.0,25.0,0.000007,78.231514,-1.311676,-2.125244,3.280617,-1.931789,-223.76889,0.00000,0.0,0.0,0.0
3,1980-01-01,0.0,27.5,0.000010,79.631010,-3.777573,-1.122395,5.743889,-1.243538,-235.55556,0.00000,0.0,0.0,0.0
4,1980-01-01,0.0,30.0,0.000010,71.573875,-5.734505,-1.362953,6.514030,-0.954163,-254.03260,0.00000,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4268766,2010-12-31,-30.0,80.0,0.000015,26.797535,25.075424,-3.653679,-1.221291,1.515594,-273.34204,296.89227,0.0,0.0,0.0
4268767,2010-12-31,-30.0,82.5,-0.000006,27.766910,24.175919,-2.866638,-6.724304,0.861771,-280.37018,296.03314,0.0,0.0,0.0
4268768,2010-12-31,-30.0,85.0,0.000010,29.111805,24.655510,-2.809170,-10.138817,0.051220,-281.05167,295.36078,0.0,0.0,0.0
4268769,2010-12-31,-30.0,87.5,0.000006,27.833050,25.088104,-2.730087,-11.036507,0.666927,-280.05610,295.10638,0.0,0.0,0.0
4268770,2010-12-31,-30.0,90.0,0.000007,15.843884,24.510345,-3.213837,-10.213325,-0.098499,-279.40427,294.44766,0.0,0.0,0.0

# images for 1980-01-01

In [4]:
df2=training_set_wt.query("time == '1980-01-01'")
df2

,time,latitude,longitude,vo,r,u_200,u_850,v_200,v_850,ttr,sst,lsm,newlsm,Tomorrow_lsm
0,1980-01-01,0.0,20.0,0.000007,80.761185,1.909660,-3.323872,1.687164,-1.823624,-247.54074,0.00000,0.0,0.0,0.0
1,1980-01-01,0.0,22.5,0.000004,80.703650,1.165733,-2.844494,1.060593,-1.991425,-240.00592,0.00000,0.0,0.0,0.0
2,1980-01-01,0.0,25.0,0.000007,78.231514,-1.311676,-2.125244,3.280617,-1.931789,-223.76889,0.00000,0.0,0.0,0.0
3,1980-01-01,0.0,27.5,0.000010,79.631010,-3.777573,-1.122395,5.743889,-1.243538,-235.55556,0.00000,0.0,0.0,0.0
4,1980-01-01,0.0,30.0,0.000010,71.573875,-5.734505,-1.362953,6.514030,-0.954163,-254.03260,0.00000,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
372,1980-01-01,-30.0,80.0,0.000026,47.806683,18.545380,-9.907837,-14.769875,-1.004082,-279.37482,296.43582,0.0,0.0,0.0
373,1980-01-01,-30.0,82.5,0.000021,51.665783,21.526130,-9.132606,-10.086578,0.732925,-279.60890,296.34772,0.0,0.0,0.0
374,1980-01-01,-30.0,85.0,0.000017,49.799970,20.898994,-7.968193,-3.871284,2.560467,-280.23703,296.39383,0.0,0.0,0.0
375,1980-01-01,-30.0,87.5,0.000011,39.725390,18.006760,-6.911251,0.549362,3.471336,-280.40594,296.30435,0.0,0.0,0.0
376,1980-01-01,-30.0,90.0,0.000015,32.036670,16.711151,-6.251347,2.342674,4.694252,-282.32890,295.99884,0.0,0.0,0.0

In [7]:
#13lat, 29long, 8variables
im = np.zeros( (13,29,8), dtype=np.float32 )

for loc in range(0,377):
    for i in range(0,13):
        for j in range(0,29):
            for k in range(0,8):
                im[i,j,k] = (df2.iloc[loc,k+3])




im

array([[[ 1.5391153e-05,  3.2036671e+01,  1.6711151e+01, ...,
          4.6942520e+00, -2.8232889e+02,  2.9599884e+02],
        [ 1.5391153e-05,  3.2036671e+01,  1.6711151e+01, ...,
          4.6942520e+00, -2.8232889e+02,  2.9599884e+02],
        [ 1.5391153e-05,  3.2036671e+01,  1.6711151e+01, ...,
          4.6942520e+00, -2.8232889e+02,  2.9599884e+02],
        ...,
        [ 1.5391153e-05,  3.2036671e+01,  1.6711151e+01, ...,
          4.6942520e+00, -2.8232889e+02,  2.9599884e+02],
        [ 1.5391153e-05,  3.2036671e+01,  1.6711151e+01, ...,
          4.6942520e+00, -2.8232889e+02,  2.9599884e+02],
        [ 1.5391153e-05,  3.2036671e+01,  1.6711151e+01, ...,
          4.6942520e+00, -2.8232889e+02,  2.9599884e+02]],

       [[ 1.5391153e-05,  3.2036671e+01,  1.6711151e+01, ...,
          4.6942520e+00, -2.8232889e+02,  2.9599884e+02],
        [ 1.5391153e-05,  3.2036671e+01,  1.6711151e+01, ...,
          4.6942520e+00, -2.8232889e+02,  2.9599884e+02],
        [ 1.5391153e-05,  3.2036671e+01,  1.6711151e+01, ...,
          4.6942520e+00, -2.8232889e+02,  2.9599884e+02],
        ...,
        [ 1.5391153e-05,  3.2036671e+01,  1.6711151e+01, ...,
          4.6942520e+00, -2.8232889e+02,  2.9599884e+02],
        [ 1.5391153e-05,  3.2036671e+01,  1.6711151e+01, ...,
          4.6942520e+00, -2.8232889e+02,  2.9599884e+02],
        [ 1.5391153e-05,  3.2036671e+01,  1.6711151e+01, ...,
          4.6942520e+00, -2.8232889e+02,  2.9599884e+02]],

       [[ 1.5391153e-05,  3.2036671e+01,  1.6711151e+01, ...,
          4.6942520e+00, -2.8232889e+02,  2.9599884e+02],
        [ 1.5391153e-05,  3.2036671e+01,  1.6711151e+01, ...,
          4.6942520e+00, -2.8232889e+02,  2.9599884e+02],
        [ 1.5391153e-05,  3.2036671e+01,  1.6711151e+01, ...,
          4.6942520e+00, -2.8232889e+02,  2.9599884e+02],
        ...,
        [ 1.5391153e-05,  3.2036671e+01,  1.6711151e+01, ...,
          4.6942520e+00, -2.8232889e+02,  2.9599884e+02],
        [ 1.5391153e-05,  3.2036671e+01,  1.6711151e+01, ...,
          4.6942520e+00, -2.8232889e+02,  2.9599884e+02],
        [ 1.5391153e-05,  3.2036671e+01,  1.6711151e+01, ...,
          4.6942520e+00, -2.8232889e+02,  2.9599884e+02]],

       ...,

       [[ 1.5391153e-05,  3.2036671e+01,  1.6711151e+01, ...,
          4.6942520e+00, -2.8232889e+02,  2.9599884e+02],
        [ 1.5391153e-05,  3.2036671e+01,  1.6711151e+01, ...,
          4.6942520e+00, -2.8232889e+02,  2.9599884e+02],
        [ 1.5391153e-05,  3.2036671e+01,  1.6711151e+01, ...,
          4.6942520e+00, -2.8232889e+02,  2.9599884e+02],
        ...,
        [ 1.5391153e-05,  3.2036671e+01,  1.6711151e+01, ...,
          4.6942520e+00, -2.8232889e+02,  2.9599884e+02],
        [ 1.5391153e-05,  3.2036671e+01,  1.6711151e+01, ...,
          4.6942520e+00, -2.8232889e+02,  2.9599884e+02],
        [ 1.5391153e-05,  3.2036671e+01,  1.6711151e+01, ...,
          4.6942520e+00, -2.8232889e+02,  2.9599884e+02]],

       [[ 1.5391153e-05,  3.2036671e+01,  1.6711151e+01, ...,
          4.6942520e+00, -2.8232889e+02,  2.9599884e+02],
        [ 1.5391153e-05,  3.2036671e+01,  1.6711151e+01, ...,
          4.6942520e+00, -2.8232889e+02,  2.9599884e+02],
        [ 1.5391153e-05,  3.2036671e+01,  1.6711151e+01, ...,
          4.6942520e+00, -2.8232889e+02,  2.9599884e+02],
        ...,
        [ 1.5391153e-05,  3.2036671e+01,  1.6711151e+01, ...,
          4.6942520e+00, -2.8232889e+02,  2.9599884e+02],
        [ 1.5391153e-05,  3.2036671e+01,  1.6711151e+01, ...,
          4.6942520e+00, -2.8232889e+02,  2.9599884e+02],
        [ 1.5391153e-05,  3.2036671e+01,  1.6711151e+01, ...,
          4.6942520e+00, -2.8232889e+02,  2.9599884e+02]],

       [[ 1.5391153e-05,  3.2036671e+01,  1.6711151e+01, ...,
          4.6942520e+00, -2.8232889e+02,  2.9599884e+02],
        [ 1.5391153e-05,  3.2036671e+01,  1.6711151e+01, ...,
          4.6942520e+00, -2.8232889e+02,  2.9599884e+02],
        [ 1.5391153e-05,  3.2036671e+01,  1.6711151e+01, ...,
          4.6942520e+00, -2.8232889e+02,  2.9599884e+02],
        ...,
        [ 1.5391153e-05,  3.2036671e+01,  1.6711151e+01, ...,
          4.6942520e+00, -2.8232889e+02,  2.9599884e+02],
        [ 1.5391153e-05,  3.2036671e+01,  1.6711151e+01, ...,
          4.6942520e+00, -2.8232889e+02,  2.9599884e+02],
        [ 1.5391153e-05,  3.2036671e+01,  1.6711151e+01, ...,
          4.6942520e+00, -2.8232889e+02,  2.9599884e+02]]], dtype=float32)

# convert tarining set to images

In [10]:
ee = training_set_wt.groupby('time')
ee.first()

,latitude,longitude,vo,r,u_200,u_850,v_200,v_850,ttr,sst,lsm,newlsm,Tomorrow_lsm
time,,,,,,,,,,,,,
1980-01-01,0.0,20.0,6.806222e-06,80.761185,1.909660,-3.323872,1.687164,-1.823624,-247.54074,0.0,0.0,0.0,0.0
1980-01-02,0.0,20.0,1.524488e-06,73.052670,2.394066,-3.260037,-0.573120,-2.649311,-255.47037,0.0,0.0,0.0,0.0
1980-01-03,0.0,20.0,1.400389e-06,74.691990,-0.650856,-1.209122,0.458076,0.156895,-229.39223,0.0,0.0,0.0,0.0
1980-01-04,0.0,20.0,-4.308575e-06,69.558365,-0.194260,1.701866,-0.181549,1.285477,-199.08223,0.0,0.0,0.0,0.0
1980-01-05,0.0,20.0,-6.312330e-07,61.294483,-5.248871,0.283085,-0.849533,0.376900,-215.34074,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2010-12-27,0.0,20.0,-3.018795e-07,66.015110,-14.098297,-0.146061,7.199135,-0.981693,-197.44390,0.0,0.0,0.0,0.0
2010-12-28,0.0,20.0,-3.764144e-06,61.938423,-15.235313,1.003487,8.526947,0.974545,-230.44556,0.0,0.0,0.0,0.0
2010-12-29,0.0,20.0,2.670524e-06,68.518585,-17.412445,-1.295174,11.475571,1.613583,-227.24629,0.0,0.0,0.0,0.0
2010-12-30,0.0,20.0,9.202922e-07,70.950810,-12.942703,-2.696281,4.099594,-0.214317,-258.33444,0.0,0.0,0.0,0.0
2010-12-31,0.0,20.0,5.950831e-06,82.348780,-0.672073,-3.158745,-0.599525,-4.595001,-228.37018,0.0,0.0,0.0,0.0

In [11]:
#training set has 11323 days
data_images_training_set = np.zeros( (11323,13,29,8), dtype=np.float32 )

for days in range(0,11323):
    print(days)
    for lat in range(0,13):
        for long in range(0,29):
            #for per in range(0,377):
            #for atr in range(0,8):
            data_images_training_set[days,:,:,:] = (training_set_wt.iloc[377*days:377*(days+1),3:11])

0
1

KeyboardInterrupt: